### PR TITLE
Pass through parameters to squarely()

### PR DESCRIPTION
**Pull request by Katiedaisey**
Adds `...` to `pairwise_pmi` to allow pass through of variables to `squarely_()`.

### CODE REVIEW

**Comment by Katiedaisey** [comment]
Pass through is present in all other `pairwise_` functions

**Comment by Katiedaisey** [comment]
AppVeyor build failed on package `colorspace` installation:

```
trying URL 'https://cran.rstudio.com/src/contrib/colorspace_1.4-0.tar.gz'
Content type 'application/x-gzip' length 2146163 bytes (2.0 MB)
==================================================
downloaded 2.0 MB
* installing *source* package 'colorspace' ...
** package 'colorspace' successfully unpacked and MD5 sums checked
** libs
*** arch - i386
c:/Rtools/mingw_32/bin/gcc  -I"c:/R/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c colorspace.c -o colorspace.o
/bin/sh: c:/Rtools/mingw_32/bin/gcc: No such file or directory
make: *** [colorspace.o] Error 127
ERROR: compilation failed for package 'colorspace'
* removing 'c:/RLibrary/colorspace'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package 'colorspace' had non-zero exit status
Calls: <Anonymous> ... with_rprofile_user -> with_envvar -> force -> force -> i.p
Execution halted
Command exited with code 1
7z a failure.zip *.Rcheck\*
```

**Comment by dgrtwo** [comment]
Good fix, thank you!

I realized after merging that we should also rerun `devtools::document()`, to update the Rd files with the `...` argument. I've done so in b2adfd289251aa4f48fa89a57b5a202e3e43ab13 so no further action needed.

**Comment by Katiedaisey** [comment]
Yes, I forgot that as well.  Thanks.

**Pull request merged**
